### ISSUE TITLE
pystac>=1.6.0 should not support python < 3.8

### ISSUE THREAD

**Issue by DManowitz** [conda-forge/pystac-feedstock#22]
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

As reported in [this issue report](https://github.com/stac-utils/pystac/issues/814) for pystac, they have dropped support for Python 3.7 starting with pystac version 1.6.0.  However, pystac 1.6.0 and one of the pystac 1.6.1 packages report python >= 3.6 as required versions.  This should be changed so these versions cannot be inadvertently installed with Python 3.7.  Additionally, no pystac v1.5.0 package is installed on conda-forge, even though this was released the same day as the v1.6.0 package.  This is particularly relevant since it is the last version of this package to support Python 3.7.

### Installed packages

```shell
Not needed.
```

### Environment info

```shell
Not needed.
```

**Comment by ocefpaf** [comment]
Do you want to send a PR to fix that?

**Comment by DManowitz** [comment]
I do not know exactly which files need to be modified to change this.  I'm just reporting this as someone who installed pystac 1.6.1 on Python 3.7 and had it not import properly.

**Comment by ocefpaf** [comment]
This is fixed in the latest version: https://github.com/conda-forge/pystac-feedstock/blob/main/recipe/meta.yaml#L14-L23

We can move the other ones to broken (easy but we may break some folks workflow) or add a repodatapatch (harder). I'll see if I can do the latter.
