### ISSUE TITLE
@conda-forge-admin, please add user @gadomski

### ISSUE THREAD

**Issue by gadomski** [conda-forge/pystac-feedstock#25]

**Comment by ocefpaf** [comment]
@gadomski thanks for your interested in helping out with pystac! In conda-forge we usually ask folks to send PRs contributing first or stating their interest in helping out. This issue does't not have the latter and I could not find the former in the feedstock history.

**Comment by gadomski** [comment]
I threw a comment on the pr: https://github.com/conda-forge/pystac-feedstock/pull/26#issuecomment-1499216491. From the feedstock side, I'm the maintainer for a couple other **stac-utils** feedstocks (https://github.com/conda-forge/stactools-feedstock/, https://github.com/conda-forge/stac-check-feedstock/). I jumped in now because we've got a bugfix release (https://github.com/stac-utils/pystac/releases/tag/v1.7.2) that it'd be nice to get onto **conda-forge** sooner rather than later, as there's some downstreams with large releases coming up that will need the bugfix.

Let me know if I can provide any more info!

**Comment by ocefpaf** [comment]
> I jumped in now because we've got a bugfix release (https://github.com/stac-utils/pystac/releases/tag/v1.7.2) that it'd be nice to get onto conda-forge sooner rather than later

Help is always welcomed. Bare in mind that, if you are OK with an interval of 1-2 hours, our bot usually catches the PyPI releases and issue a PR here without the need for a maintainer interfearence.
